// Bulk decompile all functions in the CoolscanFirmware Ghidra project
// Usage: analyzeHeadless <proj_dir> CoolscanFirmware -process -scriptPath <script_dir> -postScript bulk_decompile_firmware.java <output_file> [start_addr] [end_addr]
// If start_addr and end_addr are given, only decompiles functions in that range.

import ghidra.app.decompiler.*;
import ghidra.app.script.GhidraScript;
import ghidra.program.model.listing.*;
import ghidra.program.model.address.*;
import java.io.*;
import java.util.*;

public class bulk_decompile_firmware extends GhidraScript {

    @Override
    public void run() throws Exception {
        String[] args = getScriptArgs();
        if (args.length < 1) {
            println("Usage: bulk_decompile_firmware.java <output_file> [start_addr] [end_addr]");
            return;
        }

        String outputPath = args[0];
        long startAddr = 0;
        long endAddr = 0x80000; // Default: entire flash
        if (args.length >= 3) {
            startAddr = Long.parseLong(args[1], 16);
            endAddr = Long.parseLong(args[2], 16);
        }

        DecompInterface decomp = new DecompInterface();
        decomp.openProgram(currentProgram);

        // Set decompiler options for readable output
        DecompileOptions options = new DecompileOptions();
        decomp.setOptions(options);

        FunctionManager funcMgr = currentProgram.getFunctionManager();
        AddressFactory addrFactory = currentProgram.getAddressFactory();
        AddressSpace space = addrFactory.getDefaultAddressSpace();

        Address start = space.getAddress(startAddr);
        Address end = space.getAddress(endAddr);

        PrintWriter out = new PrintWriter(new BufferedWriter(new FileWriter(outputPath)));

        out.println("// ============================================");
        out.println("// Nikon LS-50 Firmware Decompilation");
        out.println("// Range: 0x" + String.format("%06X", startAddr) + " - 0x" + String.format("%06X", endAddr));
        out.println("// Generated by Ghidra H8/300H decompiler");
        out.println("// ============================================");
        out.println();

        // Standard H8/300H type definitions
        out.println("// H8/300H type definitions");
        out.println("typedef unsigned char  uint8_t;");
        out.println("typedef unsigned short uint16_t;");
        out.println("typedef unsigned long  uint32_t;");
        out.println("typedef signed char    int8_t;");
        out.println("typedef signed short   int16_t;");
        out.println("typedef signed long    int32_t;");
        out.println();
        out.println("// Memory-mapped I/O macros");
        out.println("#define REG8(addr)  (*(volatile uint8_t *)(addr))");
        out.println("#define REG16(addr) (*(volatile uint16_t *)(addr))");
        out.println("#define REG32(addr) (*(volatile uint32_t *)(addr))");
        out.println();

        int count = 0;
        int errors = 0;
        FunctionIterator funcIter = funcMgr.getFunctions(start, true);

        while (funcIter.hasNext()) {
            Function func = funcIter.next();
            Address funcAddr = func.getEntryPoint();

            if (funcAddr.getOffset() > endAddr) break;

            out.println("// ----------------------------------------");
            out.println("// Function: " + func.getName());
            out.println("// Address:  0x" + String.format("%06X", funcAddr.getOffset()));
            out.println("// Size:     " + func.getBody().getNumAddresses() + " bytes");

            // Get calling convention info
            Parameter[] params = func.getParameters();
            if (params.length > 0) {
                out.print("// Params:   ");
                for (int i = 0; i < params.length; i++) {
                    if (i > 0) out.print(", ");
                    out.print(params[i].getDataType().getName() + " " + params[i].getName());
                }
                out.println();
            }

            // Get callers
            Set<Function> callers = func.getCallingFunctions(monitor);
            if (!callers.isEmpty()) {
                out.print("// Called by: ");
                int callerCount = 0;
                for (Function caller : callers) {
                    if (callerCount > 0) out.print(", ");
                    out.print(caller.getName() + "@0x" + String.format("%06X", caller.getEntryPoint().getOffset()));
                    callerCount++;
                    if (callerCount >= 5) {
                        out.print(" (+" + (callers.size() - 5) + " more)");
                        break;
                    }
                }
                out.println();
            }

            // Get callees
            Set<Function> callees = func.getCalledFunctions(monitor);
            if (!callees.isEmpty()) {
                out.print("// Calls:    ");
                int calleeCount = 0;
                for (Function callee : callees) {
                    if (calleeCount > 0) out.print(", ");
                    out.print(callee.getName() + "@0x" + String.format("%06X", callee.getEntryPoint().getOffset()));
                    calleeCount++;
                    if (calleeCount >= 8) {
                        out.print(" (+" + (callees.size() - 8) + " more)");
                        break;
                    }
                }
                out.println();
            }

            out.println("// ----------------------------------------");

            try {
                DecompileResults results = decomp.decompileFunction(func, 30, monitor);
                if (results.decompileCompleted()) {
                    DecompiledFunction decFunc = results.getDecompiledFunction();
                    if (decFunc != null) {
                        out.println(decFunc.getC());
                    } else {
                        out.println("// DECOMPILE: returned null (no C output)");
                        out.println();
                    }
                } else {
                    out.println("// DECOMPILE FAILED: " + results.getErrorMessage());
                    out.println();
                    errors++;
                }
            } catch (Exception e) {
                out.println("// DECOMPILE EXCEPTION: " + e.getMessage());
                out.println();
                errors++;
            }
            count++;
        }

        out.println();
        out.println("// ============================================");
        out.println("// Total functions decompiled: " + count);
        out.println("// Decompile errors: " + errors);
        out.println("// ============================================");

        out.close();
        decomp.dispose();

        println("Decompiled " + count + " functions (" + errors + " errors) to " + outputPath);
    }
}
